### ISSUE TITLE
All Time Max and Past 12 Months Max

### ISSUE THREAD

**Issue by cwagz** [jasonacox/Powerwall-Dashboard#10]
In Grafana, would it be possible to add a panel that would look at historic maximums? This would be very useful for monitoring system performance over time.

Like a table that would show the date and time of the max production of each string in the last 12 months and then also show the date and time of the max production of each string for all time.

**Comment by jasonacox** [comment]
Interesting.  You can create a table panel and have it do some queries.  To get what you want, I think we would have to use that query to downsample the data in InfluxDB so that you get a per-day max resulting table and then use that table to get the max for all time.  I'm not sure how to capture the timestamp of that max.

No exactly what you want, but here is a per-day-max table it made for my setup:

```sql
SELECT max("A_Power") FROM "strings"."http" WHERE $timeFilter GROUP BY time(1d) fill(0) tz('America/Los_Angeles')
SELECT max("C_Power") FROM "strings"."http" WHERE $timeFilter GROUP BY time(1d) fill(0) tz('America/Los_Angeles')
SELECT max("D_Power") FROM "strings"."http" WHERE $timeFilter GROUP BY time(1d) fill(0) tz('America/Los_Angeles')
SELECT max("Inverter1") FROM "strings"."http" WHERE $timeFilter GROUP BY time(1d) fill(0) tz('America/Los_Angeles')
```

<img width="583" alt="image" src="https://user-images.githubusercontent.com/836718/156696682-40bd51d4-28bf-44fc-9b38-57b506f03e88.png">

**Comment by cwagz** [comment]
I think I am getting somewhere. I will try to post some screenshots later.

**Comment by cwagz** [comment]
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/13752647/156697924-8c902e8b-f199-4fe2-bd64-d057a4e5ad41.png">

**Comment by cwagz** [comment]
<img width="964" alt="image" src="https://user-images.githubusercontent.com/13752647/156698354-debb4047-3ff0-47c2-8e50-6022aa36c866.png">

**Comment by jasonacox** [comment]
Nice!  Can you post the queries too?

**Comment by cwagz** [comment]
```
SELECT max("A_Power") FROM "strings"."http" WHERE $timeFilter fill(0) tz('America/Los_Angeles')
SELECT max("B_Power") FROM "strings"."http" WHERE $timeFilter fill(0) tz('America/Los_Angeles')
SELECT max("A1_Power") FROM "strings"."http" WHERE $timeFilter fill(0) tz('America/Los_Angeles')

SELECT max("Inverter1") FROM "strings"."http" WHERE $timeFilter fill(0) tz('America/Los_Angeles')
SELECT max("Inverter2") FROM "strings"."http" WHERE $timeFilter fill(0) tz('America/Los_Angeles')
```
The queries are just to cover my system so I don't have all the other strings and such. I moved them down to the bottom of the Powerwall+ group:

<img width="911" alt="image" src="https://user-images.githubusercontent.com/13752647/156702465-a92361e0-e44f-4886-9b6d-90494ba27c8c.png">

**Comment by jasonacox** [comment]
Should we add a dashboard or panel section for these all time max tables?  Maybe we call it "Greatest Hits" or "HIgh Score" or "Leaderboard"? 😀

**Comment by cwagz** [comment]
This idea didn't work out too well for me. I think "cloud lensing" ends up creating false maximums. I ended up abandoning the concept. I like the ideas for names though!

**Comment by jasonacox** [comment]
That makes sense.  I'll close this for now and we can re-open if we ever think of a way to use it. :)
