### ISSUE TITLE
Invalid Interval String

### ISSUE THREAD

**Issue by dmayo305** [jasonacox/Powerwall-Dashboard#11]
I had previously installed on an older RPi 2B and all was well. Purchased a new RPi 400 (solid purchase, btw) and set up everything the same way, but now only the Live Monitoring "Energy Usage" panel is showing data. InfluxDB appears to be functioning. Here's what I get for an error:
Invalid interval string, expecting a number followed by one of "Mwdhmsy"
![GrafanaDashboardForPowerwalls](https://user-images.githubusercontent.com/13510358/156782003-4d5169d2-ffa1-4f76-847a-2d9f4fe75a84.JPG)
The only difference I can think of was I was running a headless config before, and I'm running a desktop on the RPi 400.

**Comment by dmayo305** [comment]
All stats appear normal when looked at through pyPowerwall proxy. Digging into InfluxDB now...

**Comment by jasonacox** [comment]
Hi @dmayo305 - what OS are you using?   It does look like an InfluxDB issue. I have a good test running with an RPi 4 with 32-bit Bullseye.

**Comment by dmayo305** [comment]
This has happened on 32 bit and 64 bit bullseye, both with desktop environment. The only time it didn't happen was on headless 2B running 32 bit bullseye

**Comment by dmayo305** [comment]
I noticed I don't get a GUI when attempting to access port 8086 from either local or across the network, is that a settings difference from the installation script?

**Comment by jasonacox** [comment]
Port 8086 is the InfluxDB port so there won't be a GUI there.   Can you check your InfluxDB setup in Grafana to make sure you put "5s" and not just "5" for the time interval?

Here is how:  In Grafana:
Click the "Settings" wheel ->  "Configuration" -> "Data Sources" 

<img width="207" alt="image" src="https://user-images.githubusercontent.com/836718/156866982-f310b5f2-707d-4bec-98d5-f00f333ea27f.png">

Scroll to the bottom to make sure you put in 5s (the s is important):

<img width="348" alt="image" src="https://user-images.githubusercontent.com/836718/156866957-79f4f957-f1ec-4155-a026-f50e145b4bdd.png">

**Comment by dmayo305** [comment]
> Port 8086 is the InfluxDB port so there won't be a GUI there. Can you check your InfluxDB setup in Grafana to make sure you put "5s" and not just "5" for the time interval?
> 
> Here is how: In Grafana: Click the "Settings" wheel -> "Configuration" -> "Data Sources" -> "InfluxDB"
> 
> <img alt="image" width="207" src="https://user-images.githubusercontent.com/836718/156866982-f310b5f2-707d-4bec-98d5-f00f333ea27f.png">
> 
> <img alt="image" width="265" src="https://user-images.githubusercontent.com/836718/156867050-56bf4f83-3492-4b5f-a853-d493b4f3c1f9.png">
> 
> Scroll to the bottom to make sure you put in 5s (the s is important):
> 
> <img alt="image" width="348" src="https://user-images.githubusercontent.com/836718/156866957-79f4f957-f1ec-4155-a026-f50e145b4bdd.png">

You nailed it. Not sure how I missed that! That said, reading the influx man makes one think there is a UI:
https://docs.influxdata.com/influxdb/v2.1/visualize-data/dashboards/

**Comment by jasonacox** [comment]
I'm glad that was the fix!  I should add that as a troubleshooting tip.
