### ISSUE TITLE
Update to latest on Synology - Grafana docker container restarting in a loop 

### ISSUE THREAD

**Issue by mp09** [jasonacox/Powerwall-Dashboard#137]
Looks like permission problems unexpectedly. 

<img width="960" alt="image" src="https://user-images.githubusercontent.com/107907795/203201269-0c3907e1-d812-4a29-bbb6-86b57abb74cb.png">

**Comment by BJReplay** [comment]
This is similar to the problem that I saw on WSL in #129 - I never worked out what caused this, and a couple of re-boots of the host ended up sorting it out.

**Comment by jasonacox** [comment]
A few things to try:

1) Check your compose.env file - it should have a setting for the grafana user.  You should change it to the local user (try `id` or `echo $UID` to see your current user):

```bash
GRAFANAUSER="1000:1000"
```

2) If the above is wrong, you will need to `chown -R` the ./grafana folder to the right user.  If easier, you can delete and rebuild the grafana folder (then follow [setup instructions](https://github.com/jasonacox/Powerwall-Dashboard#grafana-setup)):

```bash
docker stop grafana
docker rm grafana
rm -fr grafana
mkdir grafana
./compose-dash.sh up -d
```

**Comment by jasonacox** [comment]
That's great news!  Good job.  

Did you happen to discover what went wrong?  If so, let us know so we can add that to the project or documentation to help others.
