### ISSUE TITLE
Guidance reusing existing Grafana

### ISSUE THREAD

**Issue by fuadar** [jasonacox/Powerwall-Dashboard#171]
So i'm already running teslamate and the Grafana instance that comes with it.
i have a full docker compose working it has anyone broken down the setup.sh so we can decouple and reuse and existing  Grafana instance. i am going to download the repo and see if i can do something like it. I am planning to run this on my synology nas where i have teslamate running already

**Comment by youzer-name** [comment]
I also am running Teslamate and its Grafana instance, but I chose to keep Teslamate completely separate to keep updates on one system from breaking the other. I find it easier to just have two different Grafana instances running on different ports.
