### ISSUE TITLE
Add per string total string power generated.

### ISSUE THREAD

**Issue by brianmsailing** [jasonacox/Powerwall-Dashboard#230]
It would be great to see the total per string power generated for the time period on display as a numerical table tally.

**Comment by jasonacox** [comment]
Hi @brianmsailing !  Thanks for this suggestion. I'll add this as an enhancement request.  However, the challenge is that there are different numbers of strings per installation (I have 3 but I know others who have 8).  Currently the graphs support up to 16 but if the data is not there, it doesn't show. We would want something similar for the numerical table.  

Do you have some idea or have you attempted to add a panel to explore how we could represent that?

**Comment by brianmsailing** [comment]
Jason, thank you. Great development and amazing work by your contributors.  My suggestion was potentially simpler than I might have explained. I have not attempted to add a panel as my software development skills are not sufficient to make any changes.  My visions would be as you described a table that contains a power tally in watt's that added up the area under the curve for the displayed time adding up the total watts generated for a specific string allowing comparison between the strings for the given time.

**Comment by jasonacox** [comment]
I think I might know where you are going... I know this isn't exactly where you want to go, but this graph basically stacks all the strings in a per-day bar graph and creates totals to the right based on the duration (this is last 30 days):

<img width="842" alt="image" src="https://user-images.githubusercontent.com/836718/230542925-d2d1182a-d459-4bd3-a2e2-af36e47f2e89.png">

Last 1 year:
<img width="829" alt="image" src="https://user-images.githubusercontent.com/836718/230542994-3cab0faa-70d7-4d7b-9997-c53fb7e55390.png">



You set up each string like this:

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/836718/230542465-7561ebd9-1dfc-4330-bb73-97ca9698ff48.png">

**Comment by brianmsailing** [comment]
thank you, I was able to create based on your guidance 

SELECT integral("A_Power")  /1000/3600 FROM "strings"."http" WHERE $timeFilter
<img width="1041" alt="Screenshot 2023-04-07 at 9 12 54 AM" src="https://user-images.githubusercontent.com/15235729/230614934-9edd52aa-dae0-46a6-bd08-8efcfa161d65.png">

**Comment by jasonacox** [comment]
Awesome! Nice job @brianmsailing 

One minor note, I see the labels "Front STring KW" - but if you are using `integral()` you are actually getting the product of energy over a period of time (kW * time) = kWh.
