### ISSUE TITLE
Grafana with VPN

### ISSUE THREAD

**Issue by metaton8086** [jasonacox/Powerwall-Dashboard#245]
If I am remote and connect to my home VPN (Unifi L2TP), the dashboard will not load the tables.  The queries show the spinning circles continuously.  It works fine if I am on the LAN.  I have no issues with other sites and applications behind my VPN, just Grafana.

**Comment by jasonacox** [comment]
I know several of us use VPN without issue.  When you VPN in, do you point your browser to the same IP:port address that you use for the LAN or does your VPN do portmapping?  You need to map port 9000 and 8675.

Here is a basic (poor man's) VPN - setting up and exposing an SSH endpoint (using PubkeyAuthentication) via your internet router, then running this from remote (where x.x.x.x is the IP address of your public IP):

```
ssh -N -p 22 user@x.x.x.x -L 9000:10.0.1.26:9000 -L 8675:10.0.1.26:8675
```

**Comment by metaton8086** [comment]
Mine is ip:port.  It turns out it is not an issue at all.  My firewall was blocking the traffic over the VPN.  It identified the traffic as a "ET WEB_SERVER Possible SQL Injection Attempt".  After I whitelisted my VPN subnet, it works as expected.
