### ISSUE TITLE
Timezone not changing in setup.sh

### ISSUE THREAD

**Issue by jgleigh** [jasonacox/Powerwall-Dashboard#28]
Isn't this going to force the timezone to LA instead of pulling from the environment variables?

Delete: echo "PW_TIMEZONE=${TZ}" >> ${ENV_FILE}
Add: echo "PW_TIMEZONE=America/Los_Angeles" >> ${ENV_FILE}

**Comment by jgleigh** [comment]
Never mind, I understand how the script is working now.

**Comment by jasonacox** [comment]
Hi @jgleigh - I'll reopen this as I do believe you have found a bug.  There are two issues:

* The `setup.sh` script calls the timezone update script `tz.sh` which would not work if any of the control files are refreshed (rebased): `dashboard*.json`, `powerwall.yml`, `influxdb/influxdb.sql`, or  `pypowerwall.env`
* The `tz.sh` script is not updating all of the optional dashboard scripts (e.g. `dashboard-animation.json`).

Thanks for raising this issue.  I'll submit a fix that should address these.

**Comment by jasonacox** [comment]
I have updated `setup.sh`, `tz.sh` and `upgrade.sh` to better handle Timezone settings.  You may need to force a checkout on these files to get upgrade to work:

```bash
git checkout setup.sh
git checkout tz.sh
get checkout upgrade.sh
get checkout .gitignore
```

**Comment by jgleigh** [comment]
git checkout isn't pulling the latest commits. Not sure what I'm doing wrong here.

**Comment by jgleigh** [comment]
Never mind, did a git pull and then ran upgrade and it's all updated now.

**Comment by jasonacox** [comment]
Closing this for now.  Thanks for opening the issue and the help to get it fixed.
