### ISSUE TITLE
Time zone local to device not server?

### ISSUE THREAD

**Issue by dkerr64** [jasonacox/Powerwall-Dashboard#308]
Traveling overseas and checking on my system at home and noticed that all times are converted to the time zone of my local device. 

So as my iPhone sets itself to local my sunrise and sunset time report as 11:20am and 2:30am which is 6 hours wrong.  Similarly my graphs representing “today” start at midnight local time not midnight server time. 

Can this be configured somewhere? 

Thanks

**Comment by youzer-name** [comment]
Click on the time range selector at the top/right of the Grafana page (where it says "Last 24 hours" or "Today" etc.)

![image](https://github.com/jasonacox/Powerwall-Dashboard/assets/57046429/e715de1e-1400-4578-9d9d-334165688c99)

At the bottom, click "Change time settings"

It will show a box where you can set the time zone.

![image](https://github.com/jasonacox/Powerwall-Dashboard/assets/57046429/38c410aa-6491-48a4-ae3d-e5ef86d5327d)

**Comment by dkerr64** [comment]
Ah, thank you.  I suspected there was a setting in Grafana somewhere that I needed to change.  You saved me a lot of time by pointing me directly to it.

Thanks
David
