### ISSUE TITLE
Displayed Powerwall/Gateway firmware in dashboard is stale

### ISSUE THREAD

**Issue by ibmaster** [jasonacox/Powerwall-Dashboard#309]
What is the refresh rate for the animation pane showing the current Tesla firmware?
My system updated to 23.4.2-2 yesterday (as confirmed via Tesla's iOS app) but the dashboard is saying I'm still on 23.4.2-1:

<img width="162" alt="image" src="https://github.com/jasonacox/Powerwall-Dashboard/assets/40643856/380bf6c6-5b33-407c-8b89-e21d8a4c9e89">

**Comment by ibmaster** [comment]
Well, if I completely reload the dashboard's web page it will refresh the latest firmware version string correctly... good enough for me, closing.

**Comment by jasonacox** [comment]
It should refresh every 60s or when you reload your browser as you discovered. The code for the version refresh is here if you are using a recent dashboard.json version (you can also see it by editing the animation panel):

https://github.com/jasonacox/Powerwall-Dashboard/blob/18ff67bcb433eeaa00731c2d417bbe267202e4a8/dashboards/powerflow-animation.html#L44-L53
