### ISSUE TITLE
Influx DB Error: Unable to find Timezone Chicago

### ISSUE THREAD

**Issue by oralallen82** [jasonacox/Powerwall-Dashboard#317]
Recently upgraded to latest version, during final stages of the install I noticed in the dialog:

Add downsample continuous queries to InfluxDB...
2023/06/30 03:10:24 error: error parsing query: unable to find time zone Chicago
2023/06/30 03:10:24 error: error parsing query: unable to find time zone Chicago

After installing importing the new dashboard I noticed that a few items weren't loading, hovering over the box I got the error:

InfluxDB Error: error parsing query: unable to find time zone Chicago

![image](https://github.com/jasonacox/Powerwall-Dashboard/assets/33994774/47517e99-c1ed-455e-b4ec-c3969f6c03be)

**Comment by jasonacox** [comment]
Hi @oralallen82  - I see you closed this. Were you able to get it fixed?

**Comment by oralallen82** [comment]
I was yes.
