### ISSUE TITLE
error parsing query: unable to find time zone UTCAustralia/Melbourne

### ISSUE THREAD

**Issue by zip90** [jasonacox/Powerwall-Dashboard#325]
Hi
I am new to this forum and is not a computer expert. Thank you for the great service for creating the Jason powerwall dashboard. 
i have installed it on a win 10 OS and get the error  error parsing query: unable to find time zone UTCAustralia/Melbourne"".
please let me know how to fix it. thanks again

**Comment by BJReplay** [comment]
It's not a time one.

Australia\Melbourne or Australia\Victoria both work.

Drop the leading UTC.

**Comment by zip90** [comment]
Hi
Thank you followed your instructions.and its resolved.
