### ISSUE TITLE
Error in New PW Dashboard Solar Energy Year

### ISSUE THREAD

**Issue by aesculus** [jasonacox/Powerwall-Dashboard#330]
I noticed that on the graph legend that the grid mean was really low compared to solar and home. It looks like its taking the mean over the entire year vs amounts that are > 0 like home and solar are doing.

![image](https://github.com/jasonacox/Powerwall-Dashboard/assets/283364/933d9723-eaf9-4aaf-bf78-784c44bafd58)

Also found this error when inspecting the query:

{
  "request": {
    "method": "GET",
    "url": "api/datasources/proxy/1/query",
    "params": {
      "db": "powerwall",
      "q": "SELECT sum(\"home\") FROM \"kwh\".\"http\" WHERE (\"home\" > 0) GROUP BY time(1d) fill(null) tz('America\\/Los_Angeles');SELECT sum(\"solar\") FROM \"kwh\".\"http\" WHERE (\"solar\" > 0) GROUP BY time(1d) fill(0) tz('America\\/Los_Angeles');SELECT sum(\"from_grid\") - sum(\"to_grid\") as \"grid\" FROM \"kwh\".\"http\" WHERE time >= now() - 24h and time <= now() GROUP BY time(1d) fill(0) tz('America\\/Los_Angeles')",
      "epoch": "ms"
    },
    "data": null,
    "precision": "ms",
    "hideFromInspector": false
  },
  "response": {
    "error": "error parsing query: found \\/, expected identifier, string, number, bool at line 1, char 98",
    "message": "error parsing query: found \\/, expected identifier, string, number, bool at line 1, char 98"
  }
}

**Comment by jasonacox** [comment]
Hi @aesculus  - thanks for this.  Are you using this dashboard? 
https://github.com/jasonacox/Powerwall-Dashboard/blob/main/dashboards/dashboard.json

> I noticed that on the graph legend that the grid mean was really low compared to solar and home. It looks like its taking the mean over the entire year vs amounts that are > 0 like home and solar are doing.

Both solar and home should NOT have negative values so we remove any noise that may be caused by meters reporting negative flow.  However, for grid, you need to account for negative flow because you can push energy back to the grid. The "mean" will account for this so you could potentially have a very low or even negative mean.

> America\\/Los_Angeles

That's a typo.  The new dashboard pulls the timezone from the $tz grafana variable rather than have it hardcoded.  You might check to ensure it has the right variable value set.

<img width="526" alt="image" src="https://github.com/jasonacox/Powerwall-Dashboard/assets/836718/987393e0-b9a5-4b85-9793-e5c0234f3902">

**Comment by aesculus** [comment]
Makes sense on the negative values.

Here is my Grid Usage chart. You can see I am more of consumer and the net is way more than 863 Wh.

![image](https://github.com/jasonacox/Powerwall-Dashboard/assets/283364/4c6bdb53-5ffe-44f1-ace5-25904dc2c06c)

The tz variable is set the same as above which is appropriate for my area.

**Comment by jasonacox** [comment]
Ah, I think I see what you are saying. The mean is averaging in the 0kWh days.  We could add `WHERE ("grid" = 0)` to the query.

**Comment by aesculus** [comment]
Let me know what the query should be and I can change it on the dashboard and see if it works.

This is something you would not notice if you had a full year of data since 0 would happen like never. :-)

**Comment by aesculus** [comment]
BTW here is the query and number of results:

![image](https://github.com/jasonacox/Powerwall-Dashboard/assets/283364/eba4a954-b985-43bd-9d5c-f2e950b7aa90)

**Comment by jasonacox** [comment]
Ok, if we assume that we should always have either home, from_grid, or to_grid power usage data, we can use the sum of those to indicate the system is activated.  You can update the query by clicking "Edit":

<img width="291" alt="image" src="https://github.com/jasonacox/Powerwall-Dashboard/assets/836718/6b749c36-21c8-4e8a-a618-01f2bb866460">

Scroll down to C and update the query to be (the updated bit is highlighted here):

<img width="965" alt="image" src="https://github.com/jasonacox/Powerwall-Dashboard/assets/836718/da91fa26-8156-4d1a-931b-81111ad7c9e3">

Here is the updated query:

```sql
SELECT sum("from_grid") - sum("to_grid") as "grid" FROM "kwh"."http" WHERE ("home" + "from_grid" + "to_grid" > 0) and $timeFilter GROUP BY time(1d) fill(0) tz('$tz')
```

Click Apply

<img width="226" alt="image" src="https://github.com/jasonacox/Powerwall-Dashboard/assets/836718/568f24ec-6a8f-4cb5-8a4c-c20145ca3a9d">

Click "Save"

<img width="138" alt="image" src="https://github.com/jasonacox/Powerwall-Dashboard/assets/836718/e0baafed-396b-41c4-8963-6fdc2e09f6e2">

**Comment by aesculus** [comment]
Unfortunately still selecting 366 rows, most 0.

**Comment by jasonacox** [comment]
Bummer.  Thanks for the update. This may just be the way Grafana computes legend labels. The query doesn't seem to impact it. I'm not sure what try try next.  If you discover anything that works, let us know!

**Comment by aesculus** [comment]
Do you have a problem with this?

SELECT sum("from_grid") - sum("to_grid") as "grid" FROM "kwh"."http" WHERE $timeFilter GROUP BY time(1d) fill(0) tz('$tz')

I just changed the fill from 0 to null

![image](https://github.com/jasonacox/Powerwall-Dashboard/assets/283364/540976f8-9ba2-447d-894f-d72e6d6e4eae)

**Comment by jasonacox** [comment]
That's brilliant!  Nice job @aesculus !  I'll update the dashboard.

**Comment by aesculus** [comment]
Looks great. Another satisfied customer.
