### ISSUE TITLE
How to create an alert when powerwall reaches a certain percentage.

### ISSUE THREAD

**Issue by Homer-Rivera** [jasonacox/Powerwall-Dashboard#36]
I see that the alert tab shows up on the new grid status panel.  How would one go about adding an alert tab to the powerwall percentage panel?

![Screen Shot 2022-06-11 at 10 52 44 PM](https://user-images.githubusercontent.com/8550715/173217810-351c453a-c783-4219-bbc3-99c4128b4c96.png)

**Comment by jasonacox** [comment]
Hi @Homer-Rivera - That Grafana panel doesn't have an alert function, unfortunately.  I believe alerts need to be added to time series data graphs (allowing for warning, alert, recovery markers).  I'm not an expert on Grafana alerts so there may still be a way.

Here is an alternative.  The main *Energy Usage* graph has a charge level ("E") that you could use for alerting.

<img width="891" alt="image" src="https://user-images.githubusercontent.com/836718/173245915-69e61f15-c6aa-40c3-87e9-c5dd09e010e2.png">

Tip: One thing I do know about alerting, you need to "Save" the dashboard before alerts activate.

**Comment by Homer-Rivera** [comment]
That will work.  Thanks!
