### ISSUE TITLE
Powerwall-Dashboard failing login

### ISSUE THREAD

**Issue by billraff** [jasonacox/Powerwall-Dashboard#372]
No changes to my docker configuration but as of last night repeated login failures are causing no data to be captured. Trying to go directly to the gateway in a browser no longer presents a login but an option to download the Tesla-Pro app. Is it just me?

**Comment by jasonacox** [comment]
Hi @billraff  - please join the rest of us here: https://github.com/jasonacox/Powerwall-Dashboard/discussions/367
