### ISSUE TITLE
Grid Status, Savings, Self-Powered, Solar Energy Year panels no longer work

### ISSUE THREAD

**Issue by sassyass** [jasonacox/Powerwall-Dashboard#431]
These were all working fine last year, but about a month ago (the week before Christmas maybe?) these panels stopped working and are now spitting out errors.

![image](https://github.com/jasonacox/Powerwall-Dashboard/assets/15484580/f152a866-13a6-47dd-a30b-fa441017598b)
![image](https://github.com/jasonacox/Powerwall-Dashboard/assets/15484580/bd4b8054-7f4a-4cb9-bf5b-8292d708eb94)

When I look at them they are all giving the same error: "Status: 500. Message: InfluxDB returned error: error parsing query: found \/, expected identifier, string, number, bool at line 1, char 149"

![image](https://github.com/jasonacox/Powerwall-Dashboard/assets/15484580/a37e692d-a906-442c-8bda-e09f88b4238a)

I took a peek with Chronograph, and it does look like values are still being populated into InfluxDB:
![image](https://github.com/jasonacox/Powerwall-Dashboard/assets/15484580/b2a38004-d3e8-4e79-806d-41a78623ed02)

There was probably a pypowerwall update before this but not 100% sure; and I was waiting for more updates in case it would magically fix itself, but it's still persisted even after the latest updates.

Any help would be appreciated.

**Comment by jasonacox** [comment]
Hi @sassyass - did you import the latest `dashboard.json` and overwrite the existing one?

**Comment by sassyass** [comment]
I did import the latest `dashboard.json`, but it still gives the same errors.

**Comment by jasonacox** [comment]
Yikes. This seems more like a corruption in the influxdb. Can you try these:

```bash
# Check InfluxDB for errors
docker logs influxdb

# Run setup query to see if there are errors:
docker exec --tty influxdb sh -c "influx -import -path=/var/lib/influxdb/influxdb.sql"
```

**Comment by sassyass** [comment]
hmm I was fiddling around with the query, and it looks like it is the time range function.

I changed 
`WHERE  $timeFilter tz('$tz')`
to
`WHERE $timeFilter
GROUP BY time($__interval) fill(null)`

and that seems to mostly have fixed it; in the self-powered panel I just took out the `tz('$tz')`

**Comment by jasonacox** [comment]
Ah! Nice troubleshooting. I wonder if your timezone variable was missing. If you import the dashboard.json, the timezone should not be blank or have any spaces:

<img width="521" alt="image" src="https://github.com/jasonacox/Powerwall-Dashboard/assets/836718/b348af43-1d33-4457-9a3a-d14085591272">

**Comment by sassyass** [comment]
Hm, no it is populated and looks exactly like that, `America/Los_Angeles`
