### ISSUE TITLE
Upgrade script could use some changes

### ISSUE THREAD

**Issue by mikkyo9** [jasonacox/Powerwall-Dashboard#45]
I hadn't upgraded my setup since a much earlier version and found a few upgrade.sh issues.

Script should check for errors during steps, in my case I ran out of disk space during execution(good ole Rasp pi tiny SD cards), and the script just keeps executing after failures..oops.
You could use 'set -e' to error out on any failure, or just check return codes from critical steps.

Script should be made aware of old powerwall.yml user config prior to pypowerwall.env creation.
If the "pypowerwall.env" doesn't exist, it should check for the user environment settings already in the "powerwall.yml", and read the values to propagate them to the env file
Or, at a minimum, prompt for them to create the env file(clearly nicer to just pull them out of the yml).

BTW you might want to add a description in the readme of the various dashboards now that there are several options.

**Comment by jasonacox** [comment]
Thanks for opening the issue @mikkyo9  - all great points!  I especially like the `set -e` recommendation.  If you have time and want to submit some updates to update.sh, please feel free to submit a PR. I would love for you to get credit.
