### ISSUE TITLE
Influxdb v2 update

### ISSUE THREAD

**Issue by farberm** [jasonacox/Powerwall-Dashboard#505]
I saw you were working on a version to work with influxdb v2… were you able to get it to work?if so location of new code etc?

**Comment by jasonacox** [comment]
Hi @farberm, after consideration, I don't plan on supporting influxdb v2. Having said that, I know there are several that have been able to convert their installations to use v2. It does take significant effort and many have moved to Flux in the process. It appears InfluxDB will move away from Flux in v3 (OSS called InfluxDB Edge) and back to InfluxQL (what v1 uses) and add SQL. If v3 is open source, there may be a path to upgrade direct from v1 to v3 and I will support that. Alternatively, we may look at timescaledb or other options if we need to do the data migration anyway.
