### ISSUE TITLE
verify.sh in 4.5.1 reporting TEDAPI Vitals Capabilities Incorrectly

### ISSUE THREAD

**Issue by SCHibbard** [jasonacox/Powerwall-Dashboard#515]
Just updated from 4.3.2 to 4.5.1. You all have been busy!  Got TEDAPI connection working to get back vitals & alerts (yes!)  After install, verify.sh reports " - TEDAPI Vitals: Not Connected", however docker logs pypowerwall reports "[INFO] TEDAPI Mode Enabled for Device Vitals (hybrid)".

Looks like in pypowerwall stats the value "pw3" was added between "tedapi" & "tedapi_mode", which messes with the sed command. I believe the line

TEDAPI=`curl --silent http://localhost:$PORT/stats | sed 's/.*"tedapi": \(.*\), "tedapi_mode".*/\1/' 2>/dev/null`

should be

TEDAPI=`curl --silent http://localhost:$PORT/stats | sed 's/.*"tedapi": \(.*\), "pw3".*/\1/' 2>/dev/null`

**Comment by jasonacox** [comment]
Great find, @SCHibbard  - thank you!
