### ISSUE TITLE
Not really realted to your app but what does HvpFault mean in the alerts?

### ISSUE THREAD

**Issue by farberm** [jasonacox/Powerwall-Dashboard#524]
System connected but no solar production. See HvpFault listed in the alerts. What does it mean?

**Comment by jasonacox** [comment]
I haven't seen that one. Did you observe any odd behavior or other alerts firing at the same time?

**Comment by farberm** [comment]
No was just curiousSent from my iPhoneOn Dec 24, 2024, at 1:19 AM, Jason Cox ***@***.***> wrote:﻿
I haven't seen that one. Did you observe any odd behavior or other alerts firing at the same time?
