### ISSUE TITLE
scaling issue with 2 powerwalls

### ISSUE THREAD

**Issue by nswfugitive** [jasonacox/Powerwall-Dashboard#533]
Hi mate - thank you for a great project the initial setup was great and running like a champ.  I have a question though since adding a 2nd powerwall, The powerwall capacity graph under powerwall vitals shows the first powerwall against the overall scale (30kWh on the right) vs the second powerwall which is on the left which is just over 15kWh.  It is confusing to see them both on different scales.  Is there something I can change on grafana setup - tried a few things but the results weren't good.  Any help would be great as usual....  cheers dj

**Comment by nswfugitive** [comment]
screen shot ....
![Screenshot 2024-10-03 183927](https://github.com/user-attachments/assets/89bfde09-c1ba-4ddf-838b-e738230005c2)

**Comment by nswfugitive** [comment]
sorry - close by mistake

**Comment by jasonacox** [comment]
Hi @nswfugitive , thanks for kind note and for raising this. I know it has change a few times and I believe the intent was to separate the axis so that the left side would be nominal "full pack energy" (the capacity of the PW which can degrade over time) and the right axis to show "current charge".  The reason the axis are different is that the "current charge" (right axis) has the values stacked (PW2 stacks on top of PW1 values) so that it was eaiser to see full energy charge of the system, where the "full pack energy" is separated so that you can see the individual Powerwalls degredation levels over longer periods of time (e.g. 6mo). 

I'm open to changing it. If you happen to find a better way to represent it. Let us know what you have in mind.

**Comment by nswfugitive** [comment]
Hi Jason - I completely understand separating them, and I completely agree with the concept.  I guess the issue I have is that the PW1 capacity is on based on the left scale.  When the "usage" is based on the right, so it never really aligns, I hope I've explained this better but let me know if you need more into.  Cheers.

**Comment by nswfugitive** [comment]
I also might be running an older version, please let me know if it has been fixed.  I've tried to upgrade to the latest version but I get a message saying "You don't have the initial commit yet".

**Comment by jasonacox** [comment]
It seems you have the current version. I was not the intent to have them aligned. But I understand others may like to see it aligned. I would absolutely welcome and love for someone to explore some options and work on creating a new one.

**Comment by nswfugitive** [comment]
ok - I've made a change that I'm happy with.  Don't know if it would be liked by all.  I've added an override property to overall 2 (/^PW1/), "axis > placement" and set it to right.  It reduced the scale on the right and is showing more aligned.

**Comment by jasonacox** [comment]
Thanks @nswfugitive .  I think you could also accomplish the same thing by removing the "stacking" feature and "right" axis setting for the "Charge" datapoint which is causing the alignment issue. It should also remove the right axis. 

In the Overrides tab remove these two:

<img width="489" alt="image" src="https://github.com/user-attachments/assets/394ee29f-6d96-4c51-9017-286e790525e6">

<img width="882" alt="image" src="https://github.com/user-attachments/assets/60b6e39d-667d-498d-b330-c0ccd417ed54">

**Comment by jasonacox** [comment]
I recalls someone made a point that they wanted their Powerwall energy levels to be stacked to represent the entire system charge, versus individual Powerwalls. however as you noticed, that means the individual capacity values would never align to the stacked values. An alternative would be to add both Powerwall capacity values together and only show that line. Personally, I like them non-stacked as you can monitor them independently.

**Comment by nswfugitive** [comment]
agreed - thank you.
