### ISSUE TITLE
Error with setup.sh on macOS

### ISSUE THREAD

**Issue by jdjammer** [jasonacox/Powerwall-Dashboard#534]
**Problem**
When using macOS, the installation from setup.sh will fail with an error message during the sun and moon configuration.
sed: 1: "grafana/provisions/data ...": extra characters at the end of g command

The -i option in sed works differently on macOS (BSD sed) than on Linux (GNU sed). On macOS, sed -i expects an argument for the extension of the backup file (even if you don’t want a backup), while on Linux, this argument is optional.

Solution for macOS (BSD sed):
# Set up Sun and Moon data provider
if [ -f grafana/sunandmoon-template.yml ]; then
    cp grafana/sunandmoon-template.yml grafana/provisions/datasources/sunandmoon.yml
    sed -i '' "s@zzLAT@${LAT}@g" grafana/provisions/datasources/sunandmoon.yml
    sed -i '' "s@zzLONG@${LONG}@g" grafana/provisions/datasources/sunandmoon.yml
fi
You need to provide an empty string '' after the -i option to avoid creating a backup file. Modify your sed commands like this:

**Comment by jasonacox** [comment]
Thanks, @jdjammer !  Great catch. I know this same bug has caught us before. I. need to implement a CI test that looks for this specifica use case (sed -i). I'll submit and test a fix.

**Comment by jdjammer** [comment]
Thank you!!!
