### ISSUE TITLE
sed: can't read s@zzLAT@48.051762@g: No such file or directory

### ISSUE THREAD

**Issue by wagisdev** [jasonacox/Powerwall-Dashboard#537]
**Problem**
Fresh installation, results in sed: can't read s@zzLAT@48.051762@g: No such file or directory

**To Reproduce**
Please paste a screenshot or steps to reproduce the behavior:
1. Use Option 1 -- Quick Start
2. Select Tesla Cloud (2)
3. Run as Current User (Y)
4. Leave Time Zone Default
5. Enter email address for Tesla Account
6. Setup Dash for Solar-Only (N)
7. Do you want to setup Weather Data (Y)
8. Place API Key
9. Set Latitude
10. Set Longitude
11. Set Imperial
12.....error

sed: can't read s@zzLAT@48.051762@g: No such file or directory

**Screenshots**

**Host System**
 - Hardware: Raspberry Pi 4
 - OS: Ubuntu Server v24

**Additional context**

**Comment by jasonacox** [comment]
Thanks, @wagisdev - I push a hotfix ASAP.

**Comment by jasonacox** [comment]
Thanks for reporting this @wagisdev!  This was introduced in the last slate of bug fixes (isn't that the way it is?). I've updated the logic to the `sed -i.bak` that should work for all OS variants.
