### ISSUE TITLE
Crashing after z48 hours on RPi 2B

### ISSUE THREAD

**Issue by farberm** [jasonacox/Powerwall-Dashboard#540]
I have the latest version install on an RPi2b. It starts up fine and runs for 48 hours or so without issues. However after a few days it crashes… not sure why. Do I need to upgrade to an RPi4 or 5 or is this something else?

**Comment by jasonacox** [comment]
My RPi2 gave out a year or so ago so I can't really test anymore on that platform.  Can you describe a bit more what you mean by "crashes"?  Perhaps share the log files (e.g. `docker logs pypowerwall`)?
